default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: task_manager_to_do_list_development

test:
  <<: *default
  database: task_manager_to_do_list_test

production:
  primary: &primary_production
    <<: *default
    database: task_manager_to_do_list_production
    username: task_manager_to_do_list
    password: <%= ENV["TASK_MANAGER_TO_DO_LIST_DATABASE_PASSWORD"] %>
  # cache:
  #   <<: *primary_production
  #   database: task_manager_to_do_list_production_cache
  #   migrations_paths: db/cache_migrate
  # queue:
  #   <<: *primary_production
  #   database: task_manager_to_do_list_production_queue
  #   migrations_paths: db/queue_migrate
  # cable:
  #   <<: *primary_production
  #   database: task_manager_to_do_list_production_cable
  #   migrations_paths: db/cable_migrate
